### ISSUE TITLE
Running the project

### ISSUE THREAD

**Issue by uvindub** [anhalu/vietnamese_id_card_ocr#2]
Can you please let me know how to run this project, what is the main file

**Comment by anhalu** [comment]
you can see that on runtest.py or merger_model.py 
corner -> detect_corner.py 
text -> detect_text.py

**Comment by uvindub** [comment]
got this error.see the attachment
![Capture](https://github.com/anhalu/vietnamese_id_card_ocr/assets/131393844/57139be9-20c6-4964-a8ea-6dc9618244bd)
